Bump up to rust SDK v0.2.1
CoLearn-Dev/colink-sdk-python-dev pull request #29
Opened 2022-11-09 01:37 UTC by quwenjie

Bump to rust SDK version v0.2.1:

& fix use grpcio-tools strange build bug v1.48.0 triggered by CI: upgrade to v1.50.0

2022-11-16 08:16 UTC, camelop requested changes
Looks great! We finally refactored the structure 🎉 
Thanks and please see the detailed comment.

2022-11-16 08:16 UTC, camelop commented on colink/switch_to_generated_user.py
> +    self.__init__(coreaddr=self.core_addr, jwt=self.generate_user_and_import())
just don't... don't do this...

2022-11-16 08:16 UTC, camelop commented on colink/wait_user_init_func.py
> +        self.unsubscribe(queue_name)
?

2022-11-16 08:16 UTC, camelop commented on colink/sdk_p.py
> +        return
?

2022-11-16 08:16 UTC, camelop commented on colink/sdk_p.py
>          return
?

2022-11-16 08:16 UTC, camelop commented on colink/instant_server.py
> +    def __del(self):
rename?

2022-11-19 03:34 UTC, quwenjie commented on colink/sdk_a.py
> +def run_task_with_expiration_time(
resolved

2022-11-19 03:34 UTC, quwenjie commented on colink/sdk_a.py
> +def ca_certificate(self, ca_certificate: str):
Have moved.

2022-11-19 03:34 UTC, quwenjie commented on examples/user_exchange_jwt.py
> +from colink import CoLink
Resolved.

2022-11-19 03:44 UTC, quwenjie commented on colink/lock_key.py
> +        logging.error("Invalid token.")
Resolved.

2022-11-19 03:47 UTC, quwenjie commented on colink/switch_to_generated_user.py
> +    self.__init__(coreaddr=self.core_addr, jwt=self.generate_user_and_import())
Resolved

2022-11-19 03:48 UTC, quwenjie commented
I also tested the delete functionality of instant server and it worked well.

2022-11-19 03:54 UTC, quwenjie commented on colink/participant_id.py
> +def get_participant_id(self, participants: List[CL.Participant]) -> int:
Have synced.

2022-11-19 03:54 UTC, quwenjie commented on colink/wait_user_init_func.py
> +        self.unsubscribe(queue_name)
Resolved.

2022-11-19 03:56 UTC, quwenjie commented on colink/sdk_p.py
> +        return
Resolved.

2022-11-19 03:56 UTC, quwenjie commented on colink/sdk_p.py
>          return
Resolved.

2022-11-19 03:59 UTC, quwenjie commented on colink/instant_server.py
> +    def __del(self):
Resolved.

2022-11-19 04:06 UTC, quwenjie commented on colink/__init__.py
> +from colink.colink_pb2_grpc import CoLinkStub, CoLinkServicer
In colink_pb2_grpc there is also a CoLink class, to resolve conflict we can't import *.

2022-11-22 23:44 UTC, camelop requested changes
Most things are wonderful! Once you move that import, I think we're ready to merge.
Next, we can take a look at the automatic serialization, as well as other Rust updates.
Really appreciate the effort!

2022-11-22 23:44 UTC, camelop commented on colink/__init__.py
> +from .protocol import ProtocolOperator
Can we put this on top? It's unnatural to have import at the bottom of a file.

2022-11-23 04:47 UTC, camelop approved these changes
Looks great!

2022-11-23 04:47 UTC, merged